# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: orderer1.dfarmadmin
# #   labels:
# #     run: orderer1.dfarmadmin
# # spec:
# #   type: ClusterIP
# #   selector:
# #     name: orderer1.dfarmadmin
# #   ports:
# #   - protocol: TCP
# #     port: 7050
# #     name: grpc
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: orderer2.dfarmadmin
# #   labels:
# #     run: orderer2.dfarmadmin
# # spec:
# #   type: ClusterIP
# #   selector:
# #     name: orderer2.dfarmadmin
# #   ports:
# #   - protocol: TCP
# #     port: 7050
# #     name: grpc
# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: orderer3.dfarmadmin
# #   labels:
# #     run: orderer3.dfarmadmin
# # spec:
# #   type: ClusterIP
# #   selector:
# #     name: orderer3.dfarmadmin
# #   ports:
# #   - protocol: TCP
# #     port: 7050
# #     name: grpc    



# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer1-dfarmadmin
#   labels: {
#     component: orderer1.dfarmadmin,
#     type: orderer
#   }
# spec:
#   type: ClusterIP
#   selector:
#     component: orderer1.dfarmadmin
#     type: orderer
#   ports:
#     - port: 7050
#       targetPort: 7050
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer2-dfarmadmin
#   labels: {
#     component: orderer2.dfarmadmin,
#     type: orderer
#   }
# spec:
#   type: ClusterIP
#   selector:
#     component: orderer2.dfarmadmin
#     type: orderer
#   ports:
#     - port: 7050
#       targetPort: 7050
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer3-dfarmadmin
#   labels: {
#     component: orderer3.dfarmadmin,
#     type: orderer
#   }
# spec:
#   type: ClusterIP
#   selector:
#     component: orderer3.dfarmadmin
#     type: orderer
#   ports:
#     - port: 7050
#       targetPort: 7050
  

apiVersion: v1
kind: Service
metadata:
  name: orderer-dfarmadmin
  labels: {
    component: orderer.dfarmadmin.com,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer.dfarmadmin.com
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer2-dfarmadmin-com
  labels: {
    component: orderer2.dfarmadmin.com,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer2.dfarmadmin.com
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer3-dfarmadmin-com
  labels: {
    component: orderer3.dfarmadmin.com,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer3.dfarmadmin.com
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050 
