# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: fabrics-pvc
# spec:
#   storageClassName: nfs
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 5Gi


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-volume-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: fabricfiles    
