apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: peer1-dfarmadmin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: peer1.dfarmadmin
    spec:
      volumes:
      - name: fabricadminfiles
        persistentVolumeClaim:
          claimName: efs-volume-claim
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock

      containers:
      - name: peer
        image: hyperledger/fabric-peer:1.4.3
        command: ["sh", "-c", "peer node start"]
        dns_search: .    
        env:
        - name: TZ
          value: "America/ohio" 
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_PEER_NETWORKID
          value: nid1
        - name: CORE_PEER_ID
          value: peer1.dfarmadmin
        - name: CORE_PEER_ADDRESS
          value: peer1.dfarmadmin:7051
        - name: CORE_PEER_LISTENADDRESS
          value: 0.0.0.0:7051
        - name: CORE_PEER_EVENTS_ADDRESS
          value: 0.0.0.0:7061
        - name: CORE_PEER_CHAINCODELISTENADDRESS
          value: 0.0.0.0:7052 
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer1.dfarmadmin:7051
        - name: CORE_PEER_GOSSIP_ENDPOINT
          value: peer1.dfarmadmin:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer1.dfarmadmin:7051
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "false"
        - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
          value: "true"
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: dfarmadminMSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /fabric/crypto-config/peerOrganizations/dfarmadmin/peers/peer1.dfarmadmin/msp/
        - name: CORE_LOGGING_PEER
          value: debug
        - name: CORE_LOGGING_CAUTHDSL
          value: debug
        - name: CORE_LOGGING_GOSSIP
          value: debug
        - name: CORE_LOGGING_LEDGER
          value: debug
        - name: CORE_LOGGING_MSP
          value: info
        - name: CORE_LOGGING_POLICIES
          value: debug
        - name: CORE_LOGGING_GRPC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /fabric/crypto-config/peerOrganizations/dfarmadmin/peers/peer1.dfarmadmin/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /fabric/crypto-config/peerOrganizations/dfarmadmin/peers/peer1.dfarmadmin/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /fabric/crypto-config/peerOrganizations/dfarmadmin/peers/peer1.dfarmadmin/tls/ca.crt      
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: "CouchDB"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: "localhost:5984"
        # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
        #   value: "hyperledgeruser"
        # - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
        #   value: "hyperledgerpass"
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: ORDERER_URL
          value: orderer0-service:7050
        - name: ORDERER_URL
          value: orderer1-service:7050
        - name: ORDERER_URL
          value: orderer2-service:7050
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_VM_DOCKER_ATTACHSTDOUT
          value: "true"
        volumeMounts:
        - mountPath: /fabric
          name: fabricadminfiles
        - mountPath: /host/var/run/docker.sock
          name: dockersocket
      - name: couchdb-dfarmadmin
        image: hyperledger/fabric-couchdb:0.4.16
        # env:
        # - name: COUCHDB_USER
        #   value: "hyperledgeruser"
        # - name: COUCHDB_PASSWORD
        #   value: "hyperledgerpass"
