apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabricadmin-pv #fabric-pv
  labels:
    type: local
    name: fabricadminfiles
spec:
  storageClassName: nfs
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - timeo=600
    - retrans=2
  nfs:
    path: /
    server: fs-9f10ffe7.efs.us-east-2.amazonaws.com
