# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer
#   labels: {
#    run: orderer.dfarmadmin.com
#   }
# spec:
#   type: ClusterIP
#   selector:
#     name: orderer
#   ports:
#     - protocol: TCP
#       port: 7050
#       name: grpc  
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer2
#   labels: {
#    run: orderer2.dfarmadmin.com
#   }
# spec:
#   type: ClusterIP
#   selector:
#     name: orderer2
#   ports:
#     - protocol: TCP
#       port: 7050
#       name: grpc  
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: orderer3.dfarmadmin.com
#   labels: {
#    run: orderer3
#   }
# spec:
#   type: ClusterIP
#   selector:
#     name: orderer3
#   ports:
#     - protocol: TCP
#       port: 7050
#       name: grpc  
---
apiVersion: v1
kind: Service
metadata:
  name: orderer0-service
  labels: {
    component: orderer0-service,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer0-service
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer1-service
  labels: {
    component: orderer1-service,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer1-service
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
---
apiVersion: v1
kind: Service
metadata:
  name: orderer2-service
  labels: {
    component: orderer2-service,
    type: orderer
  }
spec:
  type: ClusterIP
  selector:
    component: orderer2-service
    type: orderer
  ports:
    - port: 7050
      targetPort: 7050
  