apiVersion: v1
kind: Service
metadata:
  name: dfarmretail-ca
  labels:
    run: dfarmretail-ca
spec:
  type: ClusterIP
  selector:
    name: dfarmretail-ca
  ports:
  - protocol: TCP
    port: 30054
    targetPort: 7054
    name: grpc
  - protocol: TCP
    port: 7054
    name: grpc1
